name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-applications:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.15',  '1.22']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - run: go test
      - run: go run calculo.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: eleyoliveira/calculado:latest